/**
 * Serbian data templates for dev seed.
 * Item templates, names, review/message text.
 */

export const SERBIAN_NAMES: Array<{ firstName: string; lastName: string }> = [
  { firstName: "Marko", lastName: "Petrović" },
  { firstName: "Ana", lastName: "Jovanović" },
  { firstName: "Nikola", lastName: "Đorđević" },
  { firstName: "Jelena", lastName: "Nikolić" },
  { firstName: "Stefan", lastName: "Marković" },
  { firstName: "Milica", lastName: "Popović" },
  { firstName: "Luka", lastName: "Stojanović" },
  { firstName: "Ivana", lastName: "Ilić" },
  { firstName: "Aleksandar", lastName: "Stanković" },
  { firstName: "Maja", lastName: "Pavlović" },
  { firstName: "Đorđe", lastName: "Milošević" },
  { firstName: "Tamara", lastName: "Radovanović" },
  { firstName: "Filip", lastName: "Todorović" },
  { firstName: "Katarina", lastName: "Kostić" },
  { firstName: "Nemanja", lastName: "Živković" },
  { firstName: "Sara", lastName: "Milenković" },
  { firstName: "Vuk", lastName: "Obradović" },
  { firstName: "Teodora", lastName: "Ristić" },
  { firstName: "Miloš", lastName: "Savić" },
  { firstName: "Nina", lastName: "Đukić" },
  { firstName: "Petar", lastName: "Vasiljević" },
  { firstName: "Mina", lastName: "Matić" },
  { firstName: "Bogdan", lastName: "Janković" },
  { firstName: "Jovana", lastName: "Tomić" },
  { firstName: "Uroš", lastName: "Lazarević" },
];

export type ItemTemplate = {
  title: string;
  description: string;
  priceRange: [number, number];
};

export const ITEM_TEMPLATES: Record<string, Array<ItemTemplate>> = {
  Alati: [
    { title: "Bušilica Bosch Professional", description: "Profesionalna bušilica sa setom burgija, idealna za kućne projekte.", priceRange: [400, 800] },
    { title: "Aku odvijač Makita", description: "18V bežični odvijač sa dve baterije i punjačem.", priceRange: [300, 600] },
    { title: "Brusilica ugaona 125mm", description: "Ugaona brusilica za sečenje i brušenje metala i kamena.", priceRange: [300, 500] },
    { title: "Vibraciona šlajferica", description: "Električna šlajferica za finu obradu drveta.", priceRange: [200, 400] },
    { title: "Set ručnog alata", description: "Komplet ručnog alata u koferu: čekić, klešta, odvijači, ključevi.", priceRange: [250, 500] },
    { title: "Električna testera kružna", description: "Kružna testera za precizno sečenje drveta do 65mm.", priceRange: [400, 700] },
    { title: "Laserski nivelator", description: "Samonivelišući laser za precizno nivelisanje. Domet 20m.", priceRange: [500, 900] },
    { title: "Kompresor vazduha 50L", description: "Kompresor sa rezervoarom od 50 litara, idealan za farbanje.", priceRange: [600, 1000] },
    { title: "Perač pod pritiskom Karcher", description: "Visokopritisni perač za pranje automobila, terasa i fasada.", priceRange: [500, 900] },
    { title: "Električna ubodna testera", description: "Ubodna testera sa regulacijom brzine za drvo i metal.", priceRange: [300, 500] },
    { title: "Akumulatorska bušilica", description: "Kompaktna bušilica 12V, lagana i praktična za svakodnevne poslove.", priceRange: [250, 450] },
    { title: "Set svrdla i bitova", description: "Profesionalni set od 100 komada za različite materijale.", priceRange: [150, 300] },
    { title: "Stega za drvo 600mm", description: "Profesionalna stega za stolariju i kućne projekte.", priceRange: [100, 200] },
    { title: "Električni hoblić", description: "Hoblic za ravnanje i zaglađivanje drvenih površina.", priceRange: [350, 600] },
    { title: "Merni alati set", description: "Metar, libela, uglomer i laserski daljinomer u koferu.", priceRange: [300, 600] },
    { title: "Pištolj za lepak", description: "Akumulatorski pištolj za topljeni lepak sa dodacima.", priceRange: [100, 200] },
    { title: "Industrijski usisivač", description: "Usisivač za građevinsku prašinu i tečnosti, 30L kapacitet.", priceRange: [400, 700] },
    { title: "Agregat za struju 2kW", description: "Prenosivi benzinski agregat za kampovanje i vanredne situacije.", priceRange: [800, 1500] },
    { title: "Zavarivač inverterski", description: "Inverterski aparat za zavarivanje elektrodom do 4mm.", priceRange: [500, 900] },
    { title: "Električni čistač za oluke", description: "Praktičan čistač za održavanje oluka bez merdevina.", priceRange: [300, 500] },
    { title: "Set za keramiku", description: "Mašina za sečenje pločica sa dijamantskim diskom.", priceRange: [400, 700] },
    { title: "Benzinska kosa za travu", description: "Motorna kosa za košenje trave i korova.", priceRange: [500, 900] },
    { title: "Šrafciger set precizni", description: "Set preciznih odvijača za elektroniku i fine radove.", priceRange: [100, 200] },
    { title: "Rotacioni laserski nivelator", description: "Profesionalni rotacioni laser za građevinske radove.", priceRange: [800, 1500] },
    { title: "Detektor metala za zid", description: "Digitalni detektor za pronalaženje žica, cevi i nosača u zidovima.", priceRange: [150, 300] },
    { title: "Multifunkcionalni alat oscilatorni", description: "Oscilatorni alat sa setom nastavaka za sečenje, brušenje i struganje.", priceRange: [300, 500] },
    { title: "Merdevine aluminijumske 3m", description: "Teleskopske aluminijumske merdevine, nosivost do 150kg.", priceRange: [400, 700] },
    { title: "Električna rendisaljka", description: "Rendisaljka za ravnanje i oblikovanje drveta.", priceRange: [350, 600] },
    { title: "Hidraulična dizalica 2t", description: "Podno dizalica za podizanje automobila do 2 tone.", priceRange: [300, 500] },
    { title: "Set za tapaciranje", description: "Pneumatska klamerica sa kompletom klamerica za nameštaj.", priceRange: [250, 450] },
  ],
  Sport: [
    { title: "Bicikl Trek Marlin 5", description: "Mountain bike u odličnom stanju, 27.5 inča, 21 brzina.", priceRange: [800, 1500] },
    { title: "Skije Atomic 170cm", description: "Karving skije sa vezovima, pogodne za srednji nivo.", priceRange: [600, 1000] },
    { title: "Veslačka daščica SUP", description: "Naduvavajući SUP sa veslom i pumpom.", priceRange: [500, 900] },
    { title: "Set za badminton", description: "Dva reketa, loptice i mreža za badminton.", priceRange: [200, 400] },
    { title: "Kajaik jednosed", description: "Jednosed kajaik sa veslom, idealan za jezero ili reku.", priceRange: [700, 1200] },
    { title: "Tegovi set 50kg", description: "Kompletni set tegova sa šipkom i bučicama.", priceRange: [400, 700] },
    { title: "Snowboard Burton 155cm", description: "Snowboard sa vezovima, pogodno za napredne.", priceRange: [600, 1000] },
    { title: "Trampolin 3m", description: "Baštenski trampolin sa zaštitnom mrežom.", priceRange: [500, 800] },
    { title: "Roleri inline veličina 42", description: "Fitness roleri sa ABEC-7 ležajevima.", priceRange: [200, 400] },
    { title: "Reket za tenis Head", description: "Profesionalni reket za tenis sa futrolom.", priceRange: [300, 500] },
    { title: "Set za ronjenje", description: "Maska, disalica i peraja za ronjenje.", priceRange: [300, 500] },
    { title: "Strunjača za jogu", description: "Profesionalna neklizajuća strunjača 6mm.", priceRange: [100, 200] },
    { title: "Dresura konopac za boks", description: "Profesionalni konopac za preskakanje sa tegovima.", priceRange: [100, 150] },
    { title: "Klupa za vežbanje", description: "Podesiva klupa za bench press i vežbe sa tegovima.", priceRange: [300, 500] },
    { title: "Set za planinarenje", description: "Ranac 60L, štapovi za planinarenje i čeona lampa.", priceRange: [400, 700] },
    { title: "Fudbalski golovi prenosivi", description: "Par prenosivih golova 3x2m za trening.", priceRange: [300, 500] },
    { title: "Električni trotinet Xiaomi", description: "Električni trotinet domet 30km, max brzina 25km/h.", priceRange: [600, 1000] },
    { title: "Ribički štap sa mašinicom", description: "Teleskopski štap 3.6m sa spin mašinicom.", priceRange: [200, 400] },
    { title: "Plivački tračci za otpor", description: "Set elastičnih traka za plivanje i vežbe u vodi.", priceRange: [100, 200] },
    { title: "Skateboard profesionalni", description: "Complete skateboard sa preciznim truckovima.", priceRange: [200, 400] },
    { title: "Šlem za bicikl", description: "Lagan šlem sa ventilacijom i LED svetlom.", priceRange: [100, 200] },
    { title: "Gumeni čamac za pecanje", description: "Naduvavajući čamac za 2 osobe sa veslima.", priceRange: [400, 700] },
    { title: "Set za streljaštvo", description: "Luk sa strelama i metom za rekreativno gađanje.", priceRange: [300, 600] },
    { title: "Hodalica za bebe sportska", description: "Sportska kolica za trčanje sa velikim točkovima.", priceRange: [300, 500] },
    { title: "Boks vreća 30kg", description: "Boks vreća sa lancima za kačenje i rukavicama.", priceRange: [300, 500] },
    { title: "Set za golf", description: "Set od 7 palica sa torbom za početnike.", priceRange: [500, 900] },
    { title: "Ping pong sto sklopivi", description: "Standardni sto za stoni tenis sa mrežicom.", priceRange: [500, 800] },
    { title: "Set za paintball", description: "Marker, maska i 500 loptica za paintball.", priceRange: [400, 700] },
    { title: "Longboard cruiser", description: "Longboard za krstajene po gradu, meka vožnja.", priceRange: [200, 400] },
    { title: "Set za hokej na travi", description: "Dva štapa i loptica za rekreativni hokej.", priceRange: [200, 350] },
  ],
  Elektronika: [
    { title: "Projektor Epson Full HD", description: "Full HD projektor za prezentacije ili kućni bioskop. 3400 lumena.", priceRange: [1000, 2000] },
    { title: "Dron DJI Mini 3", description: "Kompaktan dron sa 4K kamerom i 38min leta.", priceRange: [1200, 2000] },
    { title: "Fotoaparat Canon EOS R50", description: "Mirrorless fotoaparat sa 24MP senzorom i 4K videom.", priceRange: [1000, 1800] },
    { title: "GoPro Hero 12", description: "Akciona kamera 5.3K, vodootporna do 10m.", priceRange: [600, 1000] },
    { title: "PlayStation 5", description: "Konzola sa dva kontrolera i 3 igre.", priceRange: [800, 1200] },
    { title: "Bluetooth zvučnik JBL", description: "Prenosivi vodootporni zvučnik sa 20h baterijom.", priceRange: [200, 400] },
    { title: "Nintendo Switch OLED", description: "Prenosiva konzola sa OLED ekranom i Joy-Con kontrolerima.", priceRange: [500, 800] },
    { title: "Laptop Dell Inspiron", description: "Laptop za posao i kućnu upotrebu, i5 procesor, 16GB RAM.", priceRange: [800, 1500] },
    { title: "iPad Air M2", description: "Tablet sa M2 čipom, savršen za crtanje i multimediju.", priceRange: [800, 1400] },
    { title: "Zvučnici za kućni bioskop", description: "5.1 sistem zvučnika sa sabvuferom.", priceRange: [600, 1000] },
    { title: "Gimbal za telefon DJI OM6", description: "3-osni stabilizator za snimanje mobilnim telefonom.", priceRange: [300, 500] },
    { title: "Mikrofon studijski USB", description: "Kondenzatorski mikrofon za podcast i strimovanje.", priceRange: [200, 400] },
    { title: "Grafička tabla Wacom", description: "Grafička tabla za digitalno crtanje i dizajn.", priceRange: [300, 500] },
    { title: "Monitor 27 inča 4K", description: "IPS monitor visoke rezolucije za dizajn i rad.", priceRange: [600, 1000] },
    { title: "Eksterni hard disk 4TB", description: "Prenosivi hard disk za backup i prenos fajlova.", priceRange: [150, 300] },
    { title: "VR headset Meta Quest 3", description: "Standalone VR headset za igre i iskustva.", priceRange: [800, 1400] },
    { title: "Pametni sat Garmin Fenix", description: "Sportski sat sa GPS, pulsom i navigacijom.", priceRange: [400, 700] },
    { title: "Stampač laserski", description: "Crno-beli laserski štampač za kancelariju.", priceRange: [300, 500] },
    { title: "Ring svetlo za snimanje", description: "LED ring svetlo 18 inča sa stativom.", priceRange: [200, 400] },
    { title: "Bežične slušalice Sony WH-1000", description: "Premium slušalice sa aktivnim potiskivanjem buke.", priceRange: [400, 700] },
    { title: "Električni skuter Segway", description: "Električni skuter sa GPS praćenjem.", priceRange: [800, 1400] },
    { title: "DJ kontroler Pioneer", description: "DJ kontroler za miksovanje muzike sa softverom.", priceRange: [500, 900] },
    { title: "3D štampač Creality", description: "FDM 3D štampač za prototipove i modele.", priceRange: [600, 1000] },
    { title: "Powerbank 20000mAh", description: "Prenosiva baterija sa brzim punjenjem za telefone i tablete.", priceRange: [100, 200] },
    { title: "Tastatura mehanička RGB", description: "Gaming tastatura sa mehaničkim prekidačima.", priceRange: [200, 350] },
    { title: "Fotoaparat Polaroid instant", description: "Instant kamera sa filmom za retro fotografije.", priceRange: [200, 400] },
    { title: "E-čitač Kindle Paperwhite", description: "Čitač elektronskih knjiga sa osvetljenim ekranom.", priceRange: [200, 350] },
    { title: "Solarni panel prenosivi 100W", description: "Prenosivi solarni panel za kampovanje i vanredne situacije.", priceRange: [400, 700] },
    { title: "Robotski usisivač", description: "Pametni usisivač sa mapiranjem prostora i aplikacijom.", priceRange: [400, 700] },
    { title: "Veb kamera 4K", description: "4K veb kamera sa mikrofonom za video pozive i strimovanje.", priceRange: [200, 400] },
  ],
  "Kamp oprema": [
    { title: "Šator Coleman 4 osobe", description: "Prostran šator za 4 osobe sa zaštitom od kiše.", priceRange: [600, 1000] },
    { title: "Vreća za spavanje -10°C", description: "Zimska vreća za spavanje sa sintetičkom izolacijom.", priceRange: [300, 500] },
    { title: "Kampovska stolica sklopiva", description: "Lagana aluminijumska stolica sa držačem za čašu.", priceRange: [100, 200] },
    { title: "Hladnjak prenosivi 40L", description: "Termoelektrični hladnjak za kampovanje i putovanja.", priceRange: [400, 700] },
    { title: "Roštilj na gas prenosivi", description: "Kompaktni gas roštilj sa 2 gorionika.", priceRange: [400, 700] },
    { title: "Lampa za kampovanje LED", description: "Punjiva LED lampa 1000 lumena sa power bankom.", priceRange: [100, 200] },
    { title: "Madrac na naduvavanje", description: "Samoinflatirajući madrac za kampovanje, R-vrednost 3.5.", priceRange: [200, 400] },
    { title: "Kuvalo za kampovanje", description: "Gasno kuvalo sa vetrobranom i posuđem.", priceRange: [200, 350] },
    { title: "Hamak sa mrežom", description: "Dvostruki hamak sa mrežom protiv insekata.", priceRange: [200, 350] },
    { title: "Tenda za plažu", description: "Pop-up tenda za zaštitu od sunca na plaži.", priceRange: [150, 300] },
    { title: "Vodootporna torba 30L", description: "Vodootporna torba za kajakaše i campere.", priceRange: [100, 200] },
    { title: "Čeona lampa punjiva", description: "LED čeona lampa 600 lumena sa USB punjenjem.", priceRange: [100, 150] },
    { title: "Prijenosni tuš solarni", description: "Solarni tuš od 20L za kampovanje.", priceRange: [100, 200] },
    { title: "Set za prečišćavanje vode", description: "Filter i tablete za prečišćavanje vode u prirodi.", priceRange: [150, 300] },
    { title: "Sklopivi sto za kamp", description: "Aluminijumski sklopivi sto za 4 osobe.", priceRange: [200, 350] },
    { title: "GPS navigacija za planinu", description: "Ručni GPS uređaj sa topografskim mapama Srbije.", priceRange: [400, 700] },
    { title: "Šator za 2 osobe ultralight", description: "Ultralagan šator 1.5kg za planinare.", priceRange: [500, 800] },
    { title: "Kamp kuhinja komplet", description: "Prenosiva kuhinja sa radnom površinom i policama.", priceRange: [300, 500] },
    { title: "Sprej protiv medveda", description: "Zaštitni sprej za susrete sa divljim životinjama.", priceRange: [100, 150] },
    { title: "Prijenosni ventilator USB", description: "Mali ventilator za šator na baterije ili USB.", priceRange: [50, 100] },
    { title: "Multitool Leatherman", description: "Višenamenski alat sa 18 funkcija u kompaktnom dizajnu.", priceRange: [150, 300] },
    { title: "Termo boca 1L", description: "Nerđajuća termo boca koja drži toplotu 24h.", priceRange: [100, 200] },
    { title: "Šator za plažu sa UV zaštitom", description: "Lagan šator sa UPF 50+ zaštitom od sunca.", priceRange: [150, 250] },
    { title: "Prenosivi generator solarni", description: "Solarna stanica 300W sa baterijom za kampovanje.", priceRange: [600, 1000] },
    { title: "Set za kampovanje 2 osobe", description: "Komplet: šator, vreće za spavanje, strunjače i lampa.", priceRange: [800, 1400] },
    { title: "Kamp peć na drva", description: "Mala prenosiva peć za grejanje šatora.", priceRange: [300, 500] },
    { title: "Viseća mreža za hranu", description: "Mreža za čuvanje hrane od životinja u kampu.", priceRange: [50, 100] },
    { title: "Baterijska lampa 2000lm", description: "Moćna baterijska lampa za kampovanje i spasavanje.", priceRange: [200, 350] },
    { title: "Pokrivač za piknik", description: "Vodootporni pokrivač za piknik 200x200cm.", priceRange: [100, 200] },
    { title: "Kompas i mapa", description: "Profesionalni kompas sa priloženom topografskom mapom.", priceRange: [100, 200] },
  ],
  "Muzicki instrumenti": [
    { title: "Gitara akustična Yamaha", description: "Akustična gitara za početnike i srednji nivo.", priceRange: [300, 600] },
    { title: "Električna gitara Fender", description: "Stratocaster replika sa pojačalom.", priceRange: [500, 900] },
    { title: "Klavijatura Yamaha PSR", description: "61 dirka sa ugrađenim zvukovima i ritmovima.", priceRange: [300, 500] },
    { title: "Bubnjevi akustični set", description: "Komplet akustičnih bubnjeva sa činelama.", priceRange: [600, 1200] },
    { title: "Violina 4/4", description: "Puna veličina violina sa gudalom i futrolom.", priceRange: [300, 600] },
    { title: "Ukulele sopran", description: "Lagan instrument za početnike, topao zvuk.", priceRange: [100, 200] },
    { title: "Bas gitara sa pojačalom", description: "Električna bas gitara sa mini combo pojačalom.", priceRange: [400, 800] },
    { title: "MIDI kontroler Akai", description: "25-tastera MIDI kontroler za produkciju muzike.", priceRange: [200, 400] },
    { title: "PA sistem prenosivi", description: "Aktivan zvučnik 200W sa mikrofonom i stativom.", priceRange: [500, 900] },
    { title: "Harmonika 48 basova", description: "Harmonika za narodnu muziku sa futrolom.", priceRange: [400, 800] },
    { title: "Kondenzatorski mikrofon", description: "Studijski mikrofon za snimanje vokala i instrumenata.", priceRange: [200, 400] },
    { title: "Gitarski pedalboard", description: "Pedalboard sa 5 efekat pedala za gitaru.", priceRange: [300, 600] },
    { title: "Karaoke sistem", description: "Karaoke set sa dva bežična mikrofona i zvučnikom.", priceRange: [200, 400] },
    { title: "Digitalni klavir 88 dirki", description: "Weighted keys, zvuci klavira, sa stalkom.", priceRange: [600, 1000] },
    { title: "Frula srpska", description: "Tradicionalna srpska frula u C-duru.", priceRange: [100, 200] },
    { title: "Set udaraljki za decu", description: "Edukativni set: tamburin, ksilofon, marakas, triangl.", priceRange: [100, 200] },
    { title: "Loop stanica Boss RC-5", description: "Loop pedala za snimanje i reprodukciju petlji.", priceRange: [200, 400] },
    { title: "Audio interfejs 2-kanalni", description: "USB audio interfejs za kućni studio.", priceRange: [200, 400] },
    { title: "Truba sa futrolom", description: "Bb truba za početnike i srednji nivo.", priceRange: [300, 500] },
    { title: "Cajón bubnjar", description: "Peruanski udarački instrument za akustičke nastupe.", priceRange: [150, 300] },
    { title: "Gitarski pojačivač 15W", description: "Mali cevni pojačivač za vežbanje i manje nastupe.", priceRange: [200, 400] },
    { title: "Saksofon alto", description: "Alto saksofon sa futrolom i priborom.", priceRange: [500, 900] },
    { title: "Mandolina srpska", description: "Tradicionalna mandolina za tamburašku muziku.", priceRange: [200, 400] },
    { title: "Studio monitori par", description: "Par aktivnih studijskih monitora 5 inča.", priceRange: [400, 700] },
    { title: "Ukulele koncertni", description: "Koncertna veličina ukulele sa torbom.", priceRange: [150, 300] },
    { title: "Flauta poprečna", description: "Poprečna flauta za školu i sviranje u orkestru.", priceRange: [300, 500] },
    { title: "Elektronski bubnjevi", description: "Kompaktni elektronski bubnjevi za tiho vežbanje.", priceRange: [500, 900] },
    { title: "Set žica za gitaru", description: "Profesionalni set žica i čistač za gitaru.", priceRange: [50, 100] },
    { title: "Notni stalak sklopivi", description: "Podesivi aluminijumski stalak za note.", priceRange: [50, 100] },
    { title: "Metronom digitalni", description: "Digitalni metronom sa raznim ritmovskim obrascima.", priceRange: [50, 100] },
  ],
  "Knjige i igre": [
    { title: "Set društvenih igara", description: "Kolekcija od 5 popularnih društvenih igara.", priceRange: [200, 400] },
    { title: "Catan edicija na srpskom", description: "Osnovna igra Catan prevedena na srpski.", priceRange: [150, 300] },
    { title: "Šahovski set drveni", description: "Ručno rađeni drveni šah sa figurama.", priceRange: [200, 400] },
    { title: "Monopol specijalno izdanje", description: "Monopol Srbija specijalno izdanje.", priceRange: [100, 200] },
    { title: "Biblioteka srpskih klasika", description: "Kolekcija od 20 knjiga srpske književnosti.", priceRange: [300, 500] },
    { title: "Set za D&D početnika", description: "Starter set za Dungeons & Dragons sa kockicama.", priceRange: [200, 400] },
    { title: "Puzzle 1000 delova", description: "Set od 3 puzzla po 1000 delova raznih motiva.", priceRange: [100, 200] },
    { title: "Trivial Pursuit srpski", description: "Kviz igra sa pitanjima na srpskom jeziku.", priceRange: [150, 250] },
    { title: "Kolekcija stripova Alan Ford", description: "Komplet od 50 stripova Alan Ford.", priceRange: [200, 400] },
    { title: "Scrabble na srpskom", description: "Scrabble igra sa srpskim slovima.", priceRange: [100, 200] },
    { title: "Set za crtanje profesionalni", description: "Grafitne i akvarel olovke, blokovi, gumica.", priceRange: [200, 350] },
    { title: "LEGO Technic set", description: "LEGO Technic građevinski set 1000+ delova.", priceRange: [300, 600] },
    { title: "Karte za poker set", description: "Profesionalni poker set sa 300 žetona.", priceRange: [150, 300] },
    { title: "Enciklopedija prirode", description: "Bogato ilustrovana enciklopedija o životinjama i biljkama.", priceRange: [200, 350] },
    { title: "Set za kaligrafiju", description: "Set za početak bavljenja kaligrafijom sa priručnikom.", priceRange: [100, 200] },
    { title: "Backgammon drveni", description: "Ručno izrađen backgammon od orahovog drveta.", priceRange: [200, 400] },
    { title: "Set audijo knjiga srpski", description: "USB sa 30 srpskih audijo knjiga.", priceRange: [150, 300] },
    { title: "Rubikova kocka zbirka", description: "Set od 5 Rubikovih kocki raznih dimenzija.", priceRange: [100, 200] },
    { title: "Azul igra", description: "Strateška igra slaganja pločica za 2-4 igrača.", priceRange: [150, 250] },
    { title: "Set za origami", description: "Kolekcija papira i uputstava za 50 origami figura.", priceRange: [100, 150] },
    { title: "Risk igra strateška", description: "Klasična strateška igra osvajanja teritorija.", priceRange: [150, 300] },
    { title: "Dixit edicija", description: "Kreativna kartaška igra sa prelepo ilustrovanim kartama.", priceRange: [150, 250] },
    { title: "Sabrana dela Ive Andrića", description: "Kompletna sabrana dela u tvrdom povezu.", priceRange: [300, 500] },
    { title: "Kolekcija za bebe (0-3)", description: "Set edukativnih knjiga i igračaka za najmlađe.", priceRange: [150, 300] },
    { title: "Ticket to Ride Europa", description: "Igra pravljenja železničkih ruta po Evropi.", priceRange: [150, 300] },
    { title: "Magic The Gathering starter", description: "Starter set za MTG kartašku igru.", priceRange: [100, 200] },
    { title: "Set mapa za planinarenje", description: "Topografske karte planina Srbije 1:50000.", priceRange: [100, 200] },
    { title: "Go tabla komplet", description: "Kompletni set za igru Go sa kamenim figurama.", priceRange: [200, 400] },
    { title: "Wingspan igra", description: "Tematska igra o pticama za 1-5 igrača.", priceRange: [200, 350] },
    { title: "Set za slikanje uljem", description: "Komplet uljanih boja, platna i kistova.", priceRange: [200, 400] },
  ],
  "Kucni aparati": [
    { title: "Aparat za espresso", description: "Poluautomatski espresso aparat sa mlinom.", priceRange: [500, 900] },
    { title: "Robot kuhinja Bosch", description: "Multifunkcionalni kuhinjski robot sa dodacima.", priceRange: [400, 700] },
    { title: "Pekač hleba automatski", description: "Automatski aparat za pečenje hleba sa receptima.", priceRange: [200, 400] },
    { title: "Sokovnik Philips centrifugalni", description: "Centrifugalni sokovnik za voće i povrće.", priceRange: [200, 400] },
    { title: "Aparat za vafl", description: "Dvostruki aparat za vafle sa neprijanjajućom oblogom.", priceRange: [100, 200] },
    { title: "Blender sa posudama", description: "Blender visokih performansi sa 3 posude.", priceRange: [200, 400] },
    { title: "Pegla na paru profesionalna", description: "Profesionalna stanica za peglanje sa generatorom pare.", priceRange: [300, 500] },
    { title: "Dehidrator za hranu", description: "Dehidrator sa 5 polica za sušenje voća i povrća.", priceRange: [200, 350] },
    { title: "Ledolomac električni", description: "Električni aparat za mlevenje leda za koktele.", priceRange: [100, 200] },
    { title: "Aparat za palačinke", description: "Električna ploča za pečenje palačinki 30cm.", priceRange: [100, 200] },
    { title: "Mašina za pečenje pice", description: "Mini peć za picu sa kamenom podlogom.", priceRange: [300, 500] },
    { title: "Aparat za vakuumiranje", description: "Vakuum aparat za pakovanje hrane sa kesama.", priceRange: [150, 300] },
    { title: "Aparat za testo", description: "Mašina za pravljenje domaćeg testa za rezance.", priceRange: [200, 350] },
    { title: "Air fryer 5.5L", description: "Fritezer na vreli vazduh za zdravo kuvanje.", priceRange: [200, 400] },
    { title: "Sušilica za voće solarna", description: "Solarna sušilica za voće i bilje.", priceRange: [200, 350] },
    { title: "Aparat za kokice", description: "Retro aparat za kokice za filmske večeri.", priceRange: [100, 200] },
    { title: "Mlin za kafu električni", description: "Burr mlin za svežu kafu sa podešavanjem.", priceRange: [150, 300] },
    { title: "Ekspres lonac električni", description: "Električni ekspres lonac sa programima za kuvanje.", priceRange: [200, 400] },
    { title: "Pročišćivač vazduha HEPA", description: "Pročišćivač vazduha sa HEPA filterom za sobu do 30m².", priceRange: [300, 500] },
    { title: "Ovlaživač vazduha", description: "Ultrazvučni ovlaživač vazduha sa aromaterom.", priceRange: [100, 200] },
    { title: "Mašina za sladoled", description: "Aparat za pravljenje domaćeg sladoleda za 30 min.", priceRange: [200, 350] },
    { title: "Aparat za suši", description: "Set za pravljenje suši kod kuće sa uputstvima.", priceRange: [100, 200] },
    { title: "Električni wok tiganj", description: "Električni wok za brzo kuvanje azijskih jela.", priceRange: [200, 350] },
    { title: "Aparat za gaziranu vodu", description: "SodaStream aparat za gaziranje vode sa bocom.", priceRange: [150, 300] },
    { title: "Indukciona ploča prenosiva", description: "Prenosiva indukciona rerna za kampovanje ili vikendicu.", priceRange: [200, 350] },
    { title: "Pekmezovarka električna", description: "Električni lonac za kuvanje pekmeza i zimnice.", priceRange: [200, 400] },
    { title: "Toster dupli", description: "Dvostrani toster za sendviče sa gril pločama.", priceRange: [100, 200] },
    { title: "Aparat za krofne", description: "Mini aparat za pečenje krofni bez ulja.", priceRange: [100, 200] },
    { title: "Šivaća mašina Singer", description: "Električna šivaća mašina sa 30 programa šivenja.", priceRange: [300, 500] },
    { title: "Parni čistač Karcher", description: "Parni čistač za podove, kupatila i kuhinje.", priceRange: [300, 500] },
  ],
  Ostalo: [
    { title: "Kostim za maskenbal", description: "Kompletni kostim sa dodacima za tematsku zabavu.", priceRange: [100, 300] },
    { title: "Šivaca mašina prenosiva", description: "Mini šivaća mašina za popravke i male projekte.", priceRange: [100, 200] },
    { title: "Set za brijanje luksuzni", description: "Brijač, četka i sapun u poklon kutiji.", priceRange: [100, 200] },
    { title: "Kofer putni 75cm", description: "Čvrsti putni kofer sa točkovima i TSA bravom.", priceRange: [200, 400] },
    { title: "Dečija kolica", description: "Sportska kolica za decu do 3 godine.", priceRange: [200, 400] },
    { title: "Nosiljka za bebu", description: "Ergonomska nosiljka za bebe od 3 do 36 meseci.", priceRange: [150, 300] },
    { title: "Teleskop astronomski", description: "Refraktorski teleskop za posmatranje zvezda i planeta.", priceRange: [400, 700] },
    { title: "Šator za kućne ljubimce", description: "Prenosivi šator za pse i mačke na putovanjima.", priceRange: [100, 200] },
    { title: "Set za šminkanje profesionalni", description: "Profesionalni set šminke za posebne prilike.", priceRange: [200, 400] },
    { title: "Stolica za masažu prenosiva", description: "Prenosiva stolica za masažu za kućnu upotrebu.", priceRange: [300, 500] },
    { title: "Baštenska garnitura", description: "Set od 4 stolice i sto za baštu ili terasu.", priceRange: [400, 700] },
    { title: "Suncobran za plažu veliki", description: "Veliki suncobran sa UV zaštitom za plažu.", priceRange: [100, 200] },
    { title: "Oprema za paintball", description: "Kompletna oprema za paintball: maska, prsluk, marker.", priceRange: [300, 600] },
    { title: "Kućni planetarijum", description: "LED projektor zvezdanog neba za decu i odrasle.", priceRange: [150, 300] },
    { title: "Detektor metala", description: "Detektor metala za hobiste i tragače blaga.", priceRange: [300, 600] },
    { title: "Komplet za pletenje", description: "Set iglica, vune i uputstava za početnike.", priceRange: [100, 200] },
    { title: "Sklopivi stočić za laptop", description: "Podesivi stočić za rad u krevetu ili na kauču.", priceRange: [100, 200] },
    { title: "Dušek na naduvavanje gost", description: "Dvospratni dušek za goste sa pumpom.", priceRange: [150, 300] },
    { title: "Oprema za roštilj komplet", description: "Set alata za roštilj: viljuška, hvataljke, noževi, kecelja.", priceRange: [100, 200] },
    { title: "Set za pecanje komplet", description: "Štap, mašinica, kutija sa priborom i torba.", priceRange: [300, 500] },
    { title: "Kućni bar set", description: "Šejker, mešalica, cediljka i knjiga recepata.", priceRange: [150, 300] },
    { title: "Stativ za kameru profesionalni", description: "Profesionalni stativ za foto i video kamere.", priceRange: [200, 400] },
    { title: "Reflektor za fotografiju", description: "5-u-1 reflektor za studijsko fotografisanje.", priceRange: [100, 200] },
    { title: "Venčanica za iznajmljivanje", description: "Elegantna venčanica veličina 38-40.", priceRange: [500, 1000] },
    { title: "Smokin komplet", description: "Crni smokin sa košuljom i leptir mašnom, veličina L.", priceRange: [300, 600] },
    { title: "Svetlosna zavesa za dekor", description: "LED svetlosna zavesa 3x3m za dekoraciju prostora.", priceRange: [100, 200] },
    { title: "Set za fondue", description: "Keramički set za fondue od čokolade i sira.", priceRange: [100, 200] },
    { title: "Auto sedište za dete", description: "Dečije auto sedište 9-36kg sa ISO-FIX sistemom.", priceRange: [200, 400] },
    { title: "Krovni nosač za auto", description: "Univerzalni krovni nosač za bicikle ili kutiju.", priceRange: [200, 400] },
    { title: "Kompresor za auto 12V", description: "Prenosivi kompresor za pumpanje guma na putu.", priceRange: [100, 200] },
  ],
};

export const REVIEW_TEMPLATES: Record<number, string[]> = {
  5: [
    "Sve je bilo savršeno! Predmet u odličnom stanju, vlasnik je izuzetno ljubazan.",
    "Odlično iskustvo! Preporučujem svima.",
    "Fantastično! Bolje nego što sam očekivao/la.",
    "Perfektno stanje, brza komunikacija. Definitivno ponovo!",
    "Izuzetno zadovoljan/na. Predmet kao nov!",
    "Sve pohvale! Vlasnik veoma korektan i prijatan.",
    "Najbolje iskustvo sa iznajmljivanjem ikada! Top!",
    "Sva očekivanja ispunjena. Hvala na korektnosti!",
    "Profesionalan pristup, sve na mestu. Preporuka!",
    "Bez primedbi, sve je bilo tačno kako je opisano.",
  ],
  4: [
    "Veoma dobro iskustvo. Sitna zamerka na pakovanje, ali u celini odlično.",
    "Dobar predmet, vlasnik ljubazan. Manja ogrebotina ali ništa strašno.",
    "Sve u redu, malo kašnjenje pri preuzimanju ali korektno.",
    "Zadovoljan/na sam. Predmet funkcioniše odlično.",
    "Dobra komunikacija i korektan vlasnik. Blaga istrošenost ali OK.",
    "Uglavnom sve super, samo opis mogao biti precizniji.",
    "Fino iskustvo, predmet je radio kako treba.",
    "Solidan predmet, prijatna komunikacija. Preporučujem.",
    "Skoro perfektno, jedino je trebalo malo više pažnje pri pakovanju.",
    "Dobar kvalitet za ovu cenu. Zadovoljan/na.",
  ],
  3: [
    "Sasvim solidno. Predmet nije bio u stanju kao na slikama, ali funkcioniše.",
    "OK iskustvo. Ni dobro ni loše, prosečno.",
    "Moglo je bolje. Predmet je istrošeniji nego u opisu.",
    "Komunikacija mogla biti brža. Predmet u redu.",
    "Srednje zadovoljan/na. Cena je mogla biti niža za ovo stanje.",
    "Solidno ali bez oduševljenja. Uradio je posao.",
    "Prosečno iskustvo, ništa specijalno ali ni loše.",
    "Očekivao/la sam više za ovu cenu. Ali funkcionalno.",
  ],
  2: [
    "Razočaran/a. Predmet nije odgovarao opisu.",
    "Loša komunikacija, morao/la sam dugo čekati.",
    "Predmet je stigao oštećen. Nije bilo prijatno iskustvo.",
    "Ne bih ponovo iznajmio/la od ovog vlasnika.",
    "Ispod očekivanja. Opis je bio mnogo bolji od realnosti.",
    "Vlasnik nije bio dostupan kad je trebalo. Frustrirajuće.",
  ],
  1: [
    "Užasno iskustvo. Predmet neispravan, vlasnik ne odgovara na poruke.",
    "Potpuno razočaran/a. Nikada više.",
    "Najgore iskustvo na platformi. Ne preporučujem.",
    "Predmet potpuno neispravan, tražim povrat novca.",
    "Prevara. Opis totalno netačan.",
  ],
};

export const RENTER_REVIEW_TEMPLATES: Record<number, string[]> = {
  5: [
    "Odličan zakupac! Vratio na vreme i u savršenom stanju.",
    "Izuzetan korisnik, preporučujem svima. Korektan i tačan.",
    "Sve pohvale, predmet vraćen kao nov.",
    "Fantastičan zakupac, komunikacija na najvišem nivou.",
    "Perfektno iskustvo sa ovim zakupcem!",
  ],
  4: [
    "Veoma dobar zakupac. Malo kašnjenje pri vraćanju ali sve u redu.",
    "Korektan korisnik, predmet vraćen u dobrom stanju.",
    "Dobar zakupac, komunikacija uglavnom uredna.",
    "Uglavnom bez zamerki, preporučujem.",
    "Solidno, predmet vraćen očuvan.",
  ],
  3: [
    "Prosečno iskustvo. Predmet vraćen sa manjim tragovima upotrebe.",
    "OK zakupac, ali komunikacija mogla biti bolja.",
    "Solidno, mada je trebalo malo više pažnje.",
    "Bez većih problema, ali ni oduševljenja.",
  ],
  2: [
    "Predmet vraćen sa oštećenjem. Razočaran/a.",
    "Zakupac teško dostupan za komunikaciju.",
    "Kasnio sa vraćanjem bez obaveštenja.",
  ],
  1: [
    "Predmet vraćen jako oštećen. Ne preporučujem.",
    "Najgore iskustvo. Neodgovoran zakupac.",
  ],
};

export const MESSAGE_TEMPLATES = {
  starters: [
    "Zdravo! Zainteresovan/a sam za ovaj predmet. Da li je dostupan?",
    "Pozdrav! Mogu li da preuzmem sutra ujutru?",
    "Hej, vidim da je predmet slobodan. Koliko košta za vikend?",
    "Dobar dan! Imam pitanje u vezi sa stanjem predmeta.",
    "Zdravo, da li je moguće lično preuzimanje?",
    "Pozdrav! Da li je predmet u potpunosti funkcionalan?",
    "Hej! Zanima me da li imate popust za duži period?",
    "Dobar dan, zanima me da li dolazi sa svim dodacima?",
    "Zdravo! Koliko unapred treba da rezervišem?",
    "Pozdrav, da li je predmet dostupan sledećeg vikenda?",
    "Hej, mogu li videti još slika?",
    "Dobar dan! Da li je cena fiksna ili je pregovor moguć?",
    "Zdravo! Trebao bi mi za 3 dana, da li može?",
    "Pozdrav! Gde se tačno nalazi predmet za preuzimanje?",
    "Hej! Da li ste fleksibilni sa datumima?",
  ],
  replies: [
    "Može, vidimo se!",
    "Da, dostupan je. Javite kad vam odgovara.",
    "Naravno! Možete doći bilo kad od 9 do 18h.",
    "Da, sve funkcioniše perfektno. Dolazi sa svim dodacima.",
    "Cena je fiksna, ali za duži period mogu da napravim popust.",
    "Preuzimanje je u centru grada, dogovorićemo tačnu lokaciju.",
    "Slobodno, rezervišite i javite kad dolazite!",
    "Super, mogu da vas sačekam sutra posle podne.",
    "Hvala na interesovanju! Da, predmet je u odličnom stanju.",
    "Naravno, šaljem vam dodatne slike odmah.",
    "Može, fleksibilan sam sa vremenom preuzimanja.",
    "Da, za vikend je dostupan. Samo potvrdite datum.",
    "Važi, vidimo se u dogovoreno vreme!",
    "Sve je spremno za preuzimanje kad vam odgovara.",
    "Bez problema, možemo se dogovoriti za vreme koje vam odgovara.",
  ],
};

export const NOTIFICATION_TEMPLATES = [
  { message: "Nova rezervacija za vaš predmet!", type: "booking_pending" as const },
  { message: "Vaša rezervacija je odobrena.", type: "booking_approved" as const },
  { message: "Vaša rezervacija je odbijena.", type: "booking_rejected" as const },
  { message: "Imate novu poruku.", type: "message_received" as const },
  { message: "Predmet je isporučen zakupcu.", type: "item_delivered" as const },
  { message: "Podsetnik: rok za vraćanje predmeta je sutra.", type: "return_reminder" as const },
  { message: "Predmet je uspešno vraćen.", type: "item_returned" as const },
  { message: "Dobili ste novu ocenu od zakupca.", type: "renter_reviewed" as const },
  { message: "Dogovor o predaji je zatražen.", type: "agreement_requested" as const },
  { message: "Obe strane su se složile. Predmet je spreman za preuzimanje.", type: "booking_agreed" as const },
  { message: "Dobrodošli na podeli.rs! Istražite predmete u vašem okruženju.", type: "system" as const },
  { message: "Vaš plan je uspešno promenjen.", type: "plan_changed" as const },
];

export const CATEGORIES = [
  { name: "Alati", order: 0, isSystem: false, status: "active" as const },
  { name: "Sport", order: 1, isSystem: false, status: "active" as const },
  { name: "Elektronika", order: 2, isSystem: false, status: "active" as const },
  { name: "Kamp oprema", order: 3, isSystem: false, status: "active" as const },
  { name: "Muzicki instrumenti", order: 4, isSystem: false, status: "active" as const },
  { name: "Knjige i igre", order: 5, isSystem: false, status: "active" as const },
  { name: "Kucni aparati", order: 6, isSystem: false, status: "active" as const },
  { name: "Ostalo", order: 7, isSystem: true, status: "active" as const },
  // Pending suggestions
  { name: "Odeca i obuca", order: 8, isSystem: false, status: "pending" as const },
  { name: "Vozila i delovi", order: 9, isSystem: false, status: "pending" as const },
  { name: "Fotoaparati", order: 10, isSystem: false, status: "pending" as const },
];
